TestOlinebc/urls.py
# from django.contrib import admin
from django.urls import path
import xadmin
from django.conf.urls import url,include
from django.views.generic import TemplateView
from app.users.views import LoginView,  RegisterView,userviews,LogoutView
from app.operation.views import index,PaperListView,PaperView,SelectView,TrainView
from app.TOBC.views import history
urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('login/', LoginView.as_view(),name='login'),
	path('register/', RegisterView.as_view(), name="register"),
	path('captcha/',include('captcha.urls')),
	path('index/', index,name="index"),
	path('paperlist/', PaperListView.as_view(), name="paper_list"),
	path('paper/<paper_id>/', PaperView.as_view(), name="paper"),
	path('select/', SelectView.as_view(), name="select"),
	path('train/', TrainView.as_view(), name="train"),
	path('history/', history, name="history"),
	path('user_center/', userviews, name="user_center"),
	path('logout/', LogoutView.as_view(), name="logout"),

]

app/users/forms.py
from django import forms
from captcha.fields import CaptchaField


class LoginForm(forms.Form):
    #与前台表格的name相同
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)
    # captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


class RegisterForm(forms.Form):
    zhiwu_choices = (
		('jingli', '经理'),
		('zhiyuan', '职员'),

	)
    danwei_choices = (
		('tengxun', '腾讯'),
		('ali', '阿里'),
	)


    username = forms.IntegerField(min_value=1000000, max_value=9999999)
    # email = forms.EmailField(required=True)
    nickname = forms.CharField(required=True, max_length=10)
    password = forms.CharField(required=True, min_length=5)
    danwei = forms.ChoiceField(label='所在单位',choices=danwei_choices, required=True)
    zhiwu = forms.ChoiceField( label='本人职务', choices=zhiwu_choices, required=True)
    # captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


class UserInfoForm(forms.Form):
    gender_choices = (
		('male', '男'),
		('female', '女'),
	)
    danwei_choices = (
	    ('tengxun', '腾讯'),
	    ('ali', '阿里'),
    )

    leibie_choices = (
	    ('guanliyuan', '管理员'),
	    ('danweiguanliyuan', '单位管理员'),
	    ('kaosheng', '考生'),
    )
    zhiwu_choices = (
	    ('jingli', '经理'),
	    ('zhiyuan', '职员'),

    )
    nick_name = forms.CharField(label='姓    名',required=True, max_length=50)
    birthday = forms.DateField(label='生    日',required=True)
    gender = forms.ChoiceField(label='性    别',choices=gender_choices, required=True)
    # leibie = forms.ChoiceField(label='人员类别',choices=leibie_choices, required=True)
    danwei = forms.ChoiceField(label='所在单位',choices=danwei_choices, required=True)
    zhiwu = forms.ChoiceField( label='本人职务', choices=zhiwu_choices, required=True)

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}主页{% endblock %}</title>
 <link rel="icon" href="{% static 'img/test2.ico' %}"/>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/font-awesome-4.6.3/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'plugins/ionicons-2.0.1/css/ionicons.min.css' %}">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>

  <![endif]-->
<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">


  {% block css %}{% endblock %}

</head>

    <script language="javascript">
        //防止页面后退
        history.pushState(null, null, document.URL);
        window.addEventListener('popstate', function () {
            history.pushState(null, null, document.URL);
        });
    </script>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">ZXKS</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>在线考试系统</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static 'dist/img/avatar04.png' %}" class="user-image" alt="User Image">
              <span class="hidden-xs">欢迎,{{ user.nickname  }}</span>
            </a>
          </li>
          <!-- Control Sidebar Toggle Button -->
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">导航栏</li>
        <li class="active treeview">
          <a href="{% url 'index' %}">
            <i class="fa fa-dashboard"></i> <span>首页</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
        <li class="treeview">
          <a href="{% url 'history' %}">
            <i class="fa fa-table"></i> <span>历史成绩</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
          <li class="treeview">
          <a href="{% url 'user_center' %}">
            <i class="fa fa-table"></i> <span>个人中心</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

      {#        主体内容全放到这里！#}
      {% block content %}{% endblock %}

  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.1
    </div>
    <strong>Copyright &copy; 2019 <a target="_blank">bc</a>.</strong> All rights
    reserved.
  </footer>


</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jQueryUI/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>

    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>

    <!-- DataTable buttons -->
    <script src="{% static  'plugins/datatables/button/dataTables.buttons.min.js'%}"></script>
    <script src="{% static  'plugins/datatables/button/buttons.bootstrap.min.js'%}"></script>
    <!-- buttons 打印功能 -->
    <script src="{% static  'plugins/datatables/button/buttons.print.min.js'%}"></script>
    <!-- buttons 导出功能 -->
    <script src="{% static  'plugins/datatables/button/buttons.html5.min.js'%}"></script>
    <script src="{% static  'plugins/datatables/button/jszip.min.js'%}"></script>



{% block script %}{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}

{% block css %}

<!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">

        <style>
        #box1 {
            width: 600px;
            margin: 20px auto;
        }

        #box1 p {
            font-size: 20px;
            margin-bottom: 4px;
        }
        #box2 {
            width: 250px;
            margin: 20px auto;
        }


        #box2 p {
            font-size: 20px;
            margin-bottom: 4px;
        }
       #mydef {
            text-align: center;
        }



        .score {
            font-size: 50px;
            color: #3c8dbc;
        }


    </style>

{% endblock %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">


      <ol class="breadcrumb">
        <li><a href="{% url 'logout' %}"><i class="fa fa-dashboard"></i> 退出登录</a></li>

      </ol>
    </section>
    <!-- 考试须知 -->


<div id="mydef">
    <h1 class="score">考试须知</h1>

</div>

<div id="box1">
<p> 1.考试时间为20分钟，答完题可以点击“提交”，超出时间则自动交卷；</p>
<p> 2.考试采用100制，题型为25道单项选择，每题2分，10道判断题，每题2分，10道多选题，每题3分，多选题少选多选均不得分；</p>
<p> 3.每人每次只有一次考试机会，多次考试以最早成绩为准；</p>
<p> 4.试卷列表栏目下有“我要训练”模块，考生可进行模拟训练，不计分。</p>

</div>
    <div id="box2">
      <a   href="{% url 'paper_list' %}">
    <input class="btn btn-green"   value="开始考试  " />
      </a>
</div>
  <section class="content-header">


    </section>
{% endblock %}

{% block script %}
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>

    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>

    <!-- DataTable buttons -->
    <script src="{% static  'plugins/datatables/button/dataTables.buttons.min.js'%}"></script>
    <script src="{% static  'plugins/datatables/button/buttons.bootstrap.min.js'%}"></script>
    <!-- buttons 打印功能 -->
    <script src="{% static  'plugins/datatables/button/buttons.print.min.js'%}"></script>
    <!-- buttons 导出功能 -->
    <script src="{% static  'plugins/datatables/button/buttons.html5.min.js'%}"></script>
    <script src="{% static  'plugins/datatables/button/jszip.min.js'%}"></script>


{% endblock %}

templates/paperlist.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}试卷列表{% endblock %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="/static/css/login.css">


{% endblock %}





{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">

    </section>

    <!-- Main content -->
    <section class="content">
            <style>
        #box1 {
            width: 600px;
            margin: 90px auto;
        }

        #box1 p {
            font-size: 20px;
            margin-bottom: 4px;
        }
        #box2 {
            width: 250px;
            margin: 20px auto;
        }


        #box2 p {
            font-size: 20px;
            margin-bottom: 4px;
        }
       #mydef {
            text-align: center;
        }



        .score {
            font-size: 50px;
            color: #3c8dbc;
        }


    </style>
            <section class="content-header">

<div id="mydef">
    <h1 class="score">试卷列表</h1>

</div>
        </section>



{#    <div class="begin"><p>成功进入试题页面</p></div>#}
{#        <div id="box1">#}
{#            {% for i in papers %}#}
{#                <p>试卷名称：<a href="{% url 'paper' i.id %}">{{ i.name }}</a></p>#}
{#            {% endfor %}#}
{#        </div>#}

    <div id="box1">


    <div id="box2">
      <a   href="{% url 'select' %}">
    <input class="btn btn-green"   value="随机抽题  " />
      </a>
</div>
            <div id="box2">
      <a   href="{% url 'train' %}">
    <input class="btn btn-green"   value="我要训练  " />
      </a>
</div>


    </div>
    </section>

{% endblock %}

templates/register.html
<!DOCTYPE html>
<html>
{% load  staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>{{ title }}</title>
     <link rel="icon" href="{% static 'img/test2.ico' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>

<div class="bg" id="dialogBg"></div>

<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
{#                <a class="index-logo" href="{% url 'index' %}"></a>#}
                <h1>用户注册</h1>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                        <li><a href=""><img width="483" height="472" src="/static/images/banner/2019/banner0.jpg" /></a></li>

                        <li><a href=""><img width="483" height="472" src="/static/images/banner/2019/banner1.jpg" /></a></li>

                        <li><a href=""><img width="483" height="472" src="/static/images/banner/2019/banner2.jpg" /></a></li>

                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab1">
{#                    <h2>邮箱注册</h2>#}
                </div>

                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'register' %}" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group marb20 {% if register_form.errors.username %}errorput{% endif %}">
                            <label>考&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                            <input type="text" id="account_l" name="username" placeholder="请输入您的考号"/>
                        </div>
                        <div class="form-group marb20 {% if register_form.errors.email %}errorput{% endif %}">
                            <label>姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名</label>
                            <input  type="text"  name="nickname"    placeholder="请输入您的姓名" />
                        </div>
                        <div class="form-group marb20 ">
                            <label>单&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;位</label>
                              <select name="danwei" id="id_danwei" style="width:215px;line-height: 35px;height: 39px;font-size:14px" onchange="document.getElementById('input').value=this.value">
                                <option value="tengxun">腾讯</option>
                                <option value="ali">阿里</option>
                              </select>
                        </div>
                        <div class="form-group marb20 {% if register_form.errors.email %}errorput{% endif %}">
                            <label>职&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;务</label>
                              <select name="zhiwu" id="id_zhiwu" style="width:215px;line-height: 35px;height: 39px;font-size:14px" onchange="document.getElementById('input').value=this.value">
                                <option value="jingli">经理</option>
                                <option value="zhiyuan">职员</option>
                              </select>
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.password %}errorput{% endif %}">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"   placeholder="请输入6-20位非中文字符密码" />
                        </div>
{#                        <div class="form-group marb8 captcha1 {% if register_form.errors.captcha %}errorput{% endif %}">#}
{#                            <label>验&nbsp;证&nbsp;码</label>#}
{#                            {{ register_form.captcha }}#}
{#                        </div>#}
                        <div class="error btns" id="jsEmailTips">{% for key,error in register_form.errors.items %}
                            {{ error }}
                        {% endfor %}
                        {{ msg }}
                        </div>

                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册" />

                        {% csrf_token %}
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="{% url 'login' %}">[回到首页]</a></p>


            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>